
set show timing off .

load ../../interpreter-symbolic.maude
load ../syntax/module-thermostat-event-data.maude


mod TEST-THERMOSTAT-SYSTEM-MOD is
  including THERMOSTAT-SYSTEM-SYNTAX .
  including BEHAVIOR-SYMBOLIC-LOCATION . 
  including MODEL-TRANSITION-SYSTEM .
  including SMT-REAL-EXP .
  
  eq init  = loc([0]) .
  eq state = loc([1]) .

  op initConst : -> BoolExp .
  eq initConst = [true] .

  op initState : -> Object .
  eq initState = initialize(model) .
endm


mod TEST-THERMOSTAT-SYSTEM-HIE is
  including TEST-THERMOSTAT-SYSTEM-MOD .

  eq @m@ = ['TEST-THERMOSTAT-SYSTEM-MOD] .
endm

search [,5] {initConst || initState, false} =>+ C:GlobalSystem .

search [,5] {initConst || initState, true} =>+ C:GlobalSystem .
