/*
 * generated by Xtext 2.17.0
 */
package edu.postech.xtext.maude.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractMaudeScopeProvider extends DelegatingScopeProvider {
}
