/*
 * generated by Xtext
 */
package edu.uiuc.aadl.xtext.propspec.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class PropSpecUiModule extends edu.uiuc.aadl.xtext.propspec.ui.AbstractPropSpecUiModule {
	public PropSpecUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
