set show timing off .

load ../../interpreter-symbolic.maude
load ../syntax/Thermostat1Con_impl_Instance.maude

mod TEST-THERMOSTATCON1CON-SYSTEM is
  including THERMOSTAT1CON_IMPL_INSTANCE-MODEL-SYMBOLIC .

  op initState : -> Object .
  eq initState = initialize(initial) .

  op cinitState : -> Object .
  eq cinitState = initialize(collapse(initial)) .
endm

red initState .

search [,5] {bool(true) || initState | 0 | infty} =>+ C:GlobalSystem .

search [,5] {bool(true) || cinitState | 0 | infty} =>+ C:GlobalSystem .
