set show timing off .

load ../../interpreter-symbolic.maude
load ../syntax/module-thermostat.maude

----------------------------------------------
mod TEST-SYMBOLIC-ANALYSIS-MOD is
  including THERMOSTAT-SYSTEM .
  including MODEL-TRANSITION-SYSTEM .
  including SPECIFICATION-LANGUAGE-SEMANTICS .

  op initState : -> Object .
  eq initState = initialize(model) .

endm

mod TEST-SYMBOLIC-ANALYSIS is
  including TEST-SYMBOLIC-ANALYSIS-MOD .

  eq @m@ = ['TEST-SYMBOLIC-ANALYSIS-MOD] .
endm

search [,5]
      { eval(top . environment | ((c[e] < [[14.3]]) and (c[e] > [[1.5]])), initState) 
        || 
        initState, false}
 =>*
      {B:BoolExp || OBJ:Object, false}
 such that
      check-sat(B:BoolExp and 
                eval(top . environment | (c[e] > [[3.4]]), OBJ:Object)) .
      

search [,5]
    { eval(top . environment | ((c[e] < [[14.3]]) and (c[e] > [[1.5]])), initState)
      ||
      initState, false}
 =>*
      {B:BoolExp || OBJ:Object, false}
 such that
      check-sat(B:BoolExp and 
                eval(
                  (top | ((environment | (c[e] > [[3.4]])) 
                          and 
                          ((controller | c[curr]) > (environment | c[e])))), initState)) .
