/**
 * generated by Xtext 2.17.0
 */
package edu.postech.xtext.maude.ide;

import edu.postech.xtext.maude.ide.AbstractMaudeIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class MaudeIdeModule extends AbstractMaudeIdeModule {
}
