/**
 * generated by Xtext 2.17.0
 */
package edu.postech.xtext.maude.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import edu.postech.xtext.maude.MaudeRuntimeModule;
import edu.postech.xtext.maude.MaudeStandaloneSetup;
import edu.postech.xtext.maude.ide.MaudeIdeModule;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
@SuppressWarnings("all")
public class MaudeIdeSetup extends MaudeStandaloneSetup {
  @Override
  public Injector createInjector() {
    MaudeRuntimeModule _maudeRuntimeModule = new MaudeRuntimeModule();
    MaudeIdeModule _maudeIdeModule = new MaudeIdeModule();
    return Guice.createInjector(Modules2.mixin(_maudeRuntimeModule, _maudeIdeModule));
  }
}
