/*
 * generated by Xtext 2.17.0
 */
package edu.postech.xtext.maude


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class MaudeStandaloneSetup extends MaudeStandaloneSetupGenerated {

	def static void doSetup() {
		new MaudeStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
