/*
 * generated by Xtext 2.17.0
 */
package edu.postech.xtext.maude


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class MaudeRuntimeModule extends AbstractMaudeRuntimeModule {
}
