/*
 * generated by Xtext 2.17.0
 */
package edu.postech.xtext.maude.ui.tests;

import com.google.inject.Injector;
import edu.postech.xtext.maude.ui.internal.MaudeActivator;
import org.eclipse.xtext.testing.IInjectorProvider;

public class MaudeUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return MaudeActivator.getInstance().getInjector("edu.postech.xtext.maude.Maude");
	}

}
