/**
 * generated by Xtext
 */
package edu.uiuc.aadl.xtext.propspec.ui.quickfix;

import org.osate.xtext.aadl2.properties.ui.quickfix.PropertiesQuickfixProvider;

/**
 * Custom quickfixes.
 * 
 * See https://www.eclipse.org/Xtext/documentation/310_eclipse_support.html#quick-fixes
 */
@SuppressWarnings("all")
public class PropSpecQuickfixProvider extends PropertiesQuickfixProvider {
}
