
set show timing off .

load ../../interpreter-random.maude
load ../syntax/module-thermostat-hie.maude


---------------------------------------------
mod TEST-THERMOSTAT-SYSTEM-HIE is
  including THERMOSTAT-SYSTEM-SYNTAX .
  including MODEL-TRANSITION-SYSTEM .
  
  op initState : -> Object .
  eq initState = initialize(model) .

  op cinitState : -> Object .
  eq cinitState = initialize(collapse(model)) .
endm


rew [100] {{initState,0}} .

rew [100] {{initState,400}} .

rew [100] {{initState,800}} .

rew [100] {{initState,1200}} .


rew [100] {{cinitState,0}} .

rew [100] {{cinitState,400}} .

rew [100] {{cinitState,800}} .

rew [100] {{cinitState,1200}} .
