set show timing off .

load ../../interpreter-random.maude
load ../syntax/Thermostat2Con_impl_Instance.maude

---------------------------------------------
mod TEST-THERMOSTAT-SYSTEM is
  including THERMOSTAT2CON_IMPL_INSTANCE-MODEL .
  including MODEL-TRANSITION-SYSTEM .

  op initConst : -> BoolExp .
  eq initConst = [true] .

  op initState : -> Object .
  eq initState = initialize(initial) .

  op cinitState : -> Object .
  eq cinitState = initialize(collapse(initial)) .
endm

rew [100] {{initState,0}} .
rew [100] {{initState,800}} .
rew [100] {{initState,1600}} .

rew [100] {{cinitState,0}} .
rew [100] {{cinitState,800}} .
rew [100] {{cinitState,1600}} .
