set show timing off .

load ../../interpreter-random.maude
load ../syntax/Thermostat1Con_impl_Instance.maude

---------------------------------------------
mod TEST-THERMOSTAT-SYSTEM is
  including THERMOSTAT1CON_IMPL_INSTANCE-MODEL .
  including MODEL-TRANSITION-SYSTEM .

  op initConst : -> BoolExp .
  eq initConst = [true] .

  op initState : -> Object .
  eq initState = initialize(initial) .

  op cinitState : -> Object .
  eq cinitState = initialize(collapse(initial)) .
endm

rew [100] {{initState,0} | 0 | infty} .
rew [100] {{initState,400} | 0 | infty} .
rew [100] {{initState,800} | 0 | infty} .

rew [100] {{cinitState,0} | 0 | infty} .
rew [100] {{cinitState,400} | 0 | infty} .
rew [100] {{cinitState,800} | 0 | infty} .
