set show timing off .

load ../../interpreter-random.maude
load ../syntax/Drones2_impl_Instance.maude .

mod TEST-DRONE2-SYSTEM is
  including DRONES2_IMPL_INSTANCE-MODEL .
  including MODEL-TRANSITION-SYSTEM .

  op initState : -> Object .
  eq initState = initialize(initial) .

  op cinitState : -> Object .
  eq cinitState = initialize(collapse(initial)) .

endm

rew [100] {{initState,0} | 0 | infty} .
rew [100] {{initState,800} | 0 | infty} .
rew [100] {{initState,1600} | 0 | infty} .
rew [100] {{initState,2400} | 0 | infty} .

rew [100] {{cinitState,0} | 0 | infty} .
rew [100] {{cinitState,800} | 0 | infty} .
rew [100] {{cinitState,1600} | 0 | infty} .
rew [100] {{cinitState,2400} | 0 | infty} .
