
set show timing off .

load ../../interpreter-random.maude
load ../syntax/Airplane_nondet_Instance.maude



mod TEST-AIRPLANE_NONDET_INSTANCE-MODEL is
  including AIRPLANE_NONDET_INSTANCE-MODEL .

  op initState : -> Object .
  eq initState = initialize(initial) .

  op cinitState : -> Object .
  eq cinitState = initialize(collapse(initial)) .
endm


rew [100] {{initState,0} | 0 | infty} .

rew [100] {{initState,400} | 0 | infty} .

rew [100] {{initState,800} | 0 | infty} .

rew [100] {{initState,1200} | 0 | infty} .


rew [100] {{cinitState,0} | 0 | infty} .

rew [100] {{cinitState,400} | 0 | infty} .

rew [100] {{cinitState,800} | 0 | infty} .

rew [100] {{cinitState,1200} | 0 | infty} .
