/**
 * generated by Xtext 2.17.0
 */
package edu.postech.xtext.maude.validation;

import edu.postech.xtext.maude.validation.AbstractMaudeValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class MaudeValidator extends AbstractMaudeValidator {
}
