set show timing off .

load ../../interpreter-symbolic.maude
load ../syntax/Drones2_impl_Instance.maude

mod TEST-DRONE2-SYSTEM is
  including DRONES2_IMPL_INSTANCE-MODEL-SYMBOLIC .

  op initConst : -> BoolExp .
  eq initConst = [true] .

  op initState : -> Object .
  eq initState = initialize(initial) .

  op cinitState : -> Object .
  eq cinitState = initialize(collapse(initial)) .


  eq @m@ = ['DRONES2_IMPL_INSTANCE-MODEL-SYMBOLIC] .
endm

red initState .

search [,5] {initConst || initState, false} =>+ C:GlobalSystem .

search [,5] {initConst || initState, true} =>+ C:GlobalSystem .

search [,5] {initConst || cinitState, false} =>+ C:GlobalSystem .

search [,5] {initConst || cinitState, true} =>+ C:GlobalSystem .
