
set show timing off .

load ../../interpreter-symbolic.maude
load ../syntax/Airplane_nondet_Instance.maude


red initialize(initial) .

mod TEST-AIRPLANE_NONDET_INSTANCE-MODEL-SYMBOLIC is
    including AIRPLANE_NONDET_INSTANCE-MODEL-SYMBOLIC .
    including MERGE-BEHAVIOR-TRANSITION-SEMANTICS .

  eq @m@ = ['AIRPLANE_NONDET_INSTANCE-MODEL-SYMBOLIC] .
endm

rew [5] {[true] || initialize(initial), false} .

rew [5] {[true] || initialize(initial), true} .


search [,5] {[true] || initialize(initial), false} =>* G:GlobalSystem .

search [,5] {[true] || initialize(initial), true} =>* G:GlobalSystem .
