set show timing off .

load ../../interpreter-symbolic.maude
load ../syntax/module-thermostat.maude

----------------------------------------------
mod TEST-SYMBOLIC-ANALYSIS-MOD is
  including SYMBOLIC-ANALYSIS .
  including THERMOSTAT-SYSTEM .

  op initState : -> Object .
  eq initState = initialize(model) .

endm

mod TEST-SYMBOLIC-ANALYSIS is
  including TEST-SYMBOLIC-ANALYSIS-MOD .

  eq @m@ = ['TEST-SYMBOLIC-ANALYSIS-MOD] .
endm

search [,5]
      {lookup(initState, top . environment, (c[e] < [[14.3]]) and (c[e] > [[1.5]])) ||
	   initState,false} 
	=>+
	  {B:BoolExp ||
	   OBJ:Object,false}
	such that
	  check-sat(B:BoolExp and lookup(OBJ:Object, top . environment,  c[e] > [[3.4]])) .
