
set show timing off .

load ../../interpreter-symbolic.maude
load module-component-dynamics.maude


-------------------------------------------------------
mod TEST-ENSEMBLE-DYNAMICS is
  including TEST-ENSEMBLE-DYNAMICS-MOD .

  eq @m@ = ['TEST-ENSEMBLE-DYNAMICS-MOD] .
endm


red finalConst(obj3) .

search executeStep([true], obj3, false) =>* C:ConstConfig .

search executeStep([true], obj3, true) =>* C:ConstConfig .



