set show timing off .

load ../../interpreter-symbolic.maude

load module-ba-semantics




---------------------------------------------------
select TEST-BEHAVIOR-TRANSITION-SEMANTICS .

search execTrans(location(loc([0])) complete(loc([0])) trans(trans1) bcf) =>+ R:BATransResult .

search execTrans(location(loc([0])) complete(loc([0])) trans(trans2) bcf) =>+ R:BATransResult .

search execTrans(location(loc([0])) complete(loc([0])) trans(trans3) bcf) =>+ R:BATransResult .


