set show timing off .

load ../../interpreter-symbolic-merge2.maude
load ../syntax/module-thermostat.maude

---------------------------------------------
mod TEST-THERMOSTAT-SYSTEM-MOD is
  including THERMOSTAT-SYSTEM .
  including MODEL-TRANSITION-SYSTEM .

  op initState : -> Object .
  eq initState = initialize(model) .
endm


mod TEST-THERMOSTAT-SYSTEM is
  including TEST-THERMOSTAT-SYSTEM-MOD .

  eq @m@ = ['TEST-THERMOSTAT-SYSTEM-MOD] .
endm

red initState .

red finalConst(initState) .


search [,5] {bool(true) || initState | 0 | infty} =>+ C:GlobalSystem .

