
set show timing off .

load ../../interpreter-symbolic-merge2.maude


mod TEST-SYM-MERGE-TRANSITION-RESULT is
  including SYM-MERGE-TRANSITION-RESULT .
  pr SMT-VAR-GEN .
  pr SMT-REAL-EXP .

  ops c1 c2 c3 : -> ComponentRef .
  ops a b c d e : -> FeatureId .
endm

red symMerge(
(
    loc(r(2)) 
| 
    (a |-> (r(1) # [false] : b(0)), 
     b |-> (r(0) # b(1) : [true]), 
     c |-> (r(0) # b(2) : b(3)), 
     d |-> r(2) # [false], 
     e |-> [0] # [false])
|
    (c1 |=> r(1) # b(1),
     c2 |=> r(0) # [false],
     c3 |=> [true] # b(2))
|
    b("b",0)
|
    < "a.b",3,4 >)
;;
(    
    loc(b(0) ? r(0) : r(1)) 
| 
    (a |-> (r(1) # [false] : [false]), 
     b |-> (r(0) # [true] : [true]), 
     c |-> (r(0) # (b(0) or b(1)) : b(0)), 
     d |-> [0] # [false], 
     e |-> [0] # [false])
|
    (c1 |=> [3/4] # b(1), 
     c2 |=> r(0) # b(2), 
     c3 |=> [true] # b(2))
|
    b("a",0)
|
    < "a.b",2,3 >)
) .

