set show timing off .

load ../../interpreter-symbolic-merge2.maude
load ../syntax/Thermostat2Con_impl_Instance.maude

mod TEST-THERMOSTAT2CON2CON-SYSTEM is
  including THERMOSTAT2CON_IMPL_INSTANCE-MODEL-SYMBOLIC .

  op initState : -> Object .
  eq initState = initialize(initial) .

  op cinitState : -> Object .
  eq cinitState = initialize(collapse(initial)) .


  eq @m@ = ['THERMOSTAT2CON_IMPL_INSTANCE-MODEL-SYMBOLIC] .
endm

red initState .

search [,3] {bool(true) || initState | 0 | infty} =>+ C:GlobalSystem .

search [,3] {bool(true) || cinitState | 0 | infty} =>+ C:GlobalSystem .
