
set show timing off .

load ../../interpreter-symbolic-merge2.maude

load ../symbolic/module-ba-semantics.maude


-------------------------------------------------
mod TEST-BEHAVIOR-TRANSITION-SEMANTICS-META is
  including TEST-BEHAVIOR-TRANSITION-SEMANTICS .
  including BEHAVIOR-TRANSITION-SEMANTICS .

  eq @m@ = ['TEST-BEHAVIOR-TRANSITION-SEMANTICS-META] .
endm


red execTrans(location(loc(real(0))) complete(loc(real(0))) trans(trans1) bcf) .

red execTrans(location(loc(real(0))) complete(loc(real(0))) trans(trans2) bcf) .

red execTrans(location(loc(real(0))) complete(loc(real(0))) trans(trans3) bcf) .
