set show timing off .

load ../../interpreter-smt-check-symbolic.maude
load ../syntax/Thermostat2Con_impl_Instance.maude

mod TEST-THERMOSTAT2CON2CON-SYSTEM is
  including THERMOSTAT2CON_IMPL_INSTANCE-MODEL-SYMBOLIC .

  op initConst : -> BoolExp .
  eq initConst = [true] .

  op initState : -> Object .
  eq initState = initialize(initial) .

  op cinitState : -> Object .
  eq cinitState = initialize(collapse(initial)) .


  eq @m@ = ['THERMOSTAT2CON_IMPL_INSTANCE-MODEL-SYMBOLIC] .
  eq MFlag = true .
endm

red initState .

search {initConst || initState, 0, 3} =>+ C:GlobalSystem .

search {initConst || initState, 0, 3} =>+ C:GlobalSystem .

search {initConst || cinitState, 0, 3} =>+ C:GlobalSystem .

search {initConst || cinitState, 0, 3} =>+ C:GlobalSystem .
