
set show timing off .

load ../../interpreter-smt-check-symbolic.maude
load ../syntax/Airplane_nondet_Instance.maude


red initialize(initial) .

mod TEST-AIRPLANE_NONDET_INSTANCE-MODEL-SYMBOLIC is
    including AIRPLANE_NONDET_INSTANCE-MODEL-SYMBOLIC .
    including MERGE-BEHAVIOR-TRANSITION-SEMANTICS .

  eq @m@ = ['AIRPLANE_NONDET_INSTANCE-MODEL-SYMBOLIC] .
  eq MFlag = true .
endm

rew {[true] || initialize(initial), 0, 5} .

rew {[true] || initialize(initial), 0, 5} .


search {[true] || initialize(initial), 0, 5} =>* G:GlobalSystem .

search {[true] || initialize(initial), 0, 5} =>* G:GlobalSystem .
