set show timing off .

load ../../interpreter-smt-check-symbolic.maude
load ../syntax/module-thermostat.maude

---------------------------------------------
mod TEST-THERMOSTAT-SYSTEM-MOD is
  including THERMOSTAT-SYSTEM .
  including MODEL-TRANSITION-SYSTEM .

  op initConst : -> BoolExp .
  eq initConst =
        [true] .

  op initState : -> Object .
  eq initState = initialize(model) .
endm


mod TEST-THERMOSTAT-SYSTEM is
  including TEST-THERMOSTAT-SYSTEM-MOD .

  eq @m@ = ['TEST-THERMOSTAT-SYSTEM-MOD] .
  eq MFlag = true .
endm

red initState .

red finalConst(initState) .


search {initConst || initState, 0, 5} =>+ C:GlobalSystem .

search {initConst || initState, 0, 5} =>+ C:GlobalSystem .
