/**
 * generated by Xtext 2.17.0
 */
package edu.postech.xtext.maude.ui;

import edu.postech.xtext.maude.ui.AbstractMaudeUiModule;
import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class MaudeUiModule extends AbstractMaudeUiModule {
  public MaudeUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
