/*
 * generated by Xtext 2.17.0
 */
package edu.postech.xtext.maude.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class MaudeAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("edu/postech/xtext/maude/parser/antlr/internal/InternalMaude.tokens");
	}
}
