
set show timing off .

load ../../interpreter-distributed.maude
load ../syntax/module-thermostat-event-data-noparam.maude


mod TEST-THERMOSTAT-SYSTEM is
  including THERMOSTAT-SYSTEM-SYNTAX .
  including MODEL-TRANSITION-SYSTEM .

  var T : Time .
  
  op initState : -> Object .
  eq initState = initialize(model) .
endm

rew  [100] {initState | 0 | infty} .

--- count the number of reachable states up to time 25
search [,5] {initState | 0 | infty} =>* {none | T:Time | infty} .
