/**
 * generated by Xtext 2.17.0
 */
package edu.postech.xtext.maude.maude;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see edu.postech.xtext.maude.maude.MaudeFactory
 * @model kind="package"
 * @generated
 */
public interface MaudePackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "maude";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.postech.edu/xtext/maude/Maude";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "maude";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  MaudePackage eINSTANCE = edu.postech.xtext.maude.maude.impl.MaudePackageImpl.init();

  /**
   * The meta object id for the '{@link edu.postech.xtext.maude.maude.impl.ModelImpl <em>Model</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see edu.postech.xtext.maude.maude.impl.ModelImpl
   * @see edu.postech.xtext.maude.maude.impl.MaudePackageImpl#getModel()
   * @generated
   */
  int MODEL = 0;

  /**
   * The feature id for the '<em><b>Path</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL__PATH = 0;

  /**
   * The feature id for the '<em><b>Maude</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL__MAUDE = 1;

  /**
   * The feature id for the '<em><b>Options</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL__OPTIONS = 2;

  /**
   * The number of structural features of the '<em>Model</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL_FEATURE_COUNT = 3;


  /**
   * Returns the meta object for class '{@link edu.postech.xtext.maude.maude.Model <em>Model</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Model</em>'.
   * @see edu.postech.xtext.maude.maude.Model
   * @generated
   */
  EClass getModel();

  /**
   * Returns the meta object for the attribute '{@link edu.postech.xtext.maude.maude.Model#getPath <em>Path</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Path</em>'.
   * @see edu.postech.xtext.maude.maude.Model#getPath()
   * @see #getModel()
   * @generated
   */
  EAttribute getModel_Path();

  /**
   * Returns the meta object for the attribute '{@link edu.postech.xtext.maude.maude.Model#getMaude <em>Maude</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Maude</em>'.
   * @see edu.postech.xtext.maude.maude.Model#getMaude()
   * @see #getModel()
   * @generated
   */
  EAttribute getModel_Maude();

  /**
   * Returns the meta object for the attribute list '{@link edu.postech.xtext.maude.maude.Model#getOptions <em>Options</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>Options</em>'.
   * @see edu.postech.xtext.maude.maude.Model#getOptions()
   * @see #getModel()
   * @generated
   */
  EAttribute getModel_Options();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  MaudeFactory getMaudeFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link edu.postech.xtext.maude.maude.impl.ModelImpl <em>Model</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see edu.postech.xtext.maude.maude.impl.ModelImpl
     * @see edu.postech.xtext.maude.maude.impl.MaudePackageImpl#getModel()
     * @generated
     */
    EClass MODEL = eINSTANCE.getModel();

    /**
     * The meta object literal for the '<em><b>Path</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute MODEL__PATH = eINSTANCE.getModel_Path();

    /**
     * The meta object literal for the '<em><b>Maude</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute MODEL__MAUDE = eINSTANCE.getModel_Maude();

    /**
     * The meta object literal for the '<em><b>Options</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute MODEL__OPTIONS = eINSTANCE.getModel_Options();

  }

} //MaudePackage
