/**
 * generated by Xtext 2.17.0
 */
package edu.postech.xtext.maude.maude;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Model</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link edu.postech.xtext.maude.maude.Model#getPath <em>Path</em>}</li>
 *   <li>{@link edu.postech.xtext.maude.maude.Model#getMaude <em>Maude</em>}</li>
 *   <li>{@link edu.postech.xtext.maude.maude.Model#getOptions <em>Options</em>}</li>
 * </ul>
 *
 * @see edu.postech.xtext.maude.maude.MaudePackage#getModel()
 * @model
 * @generated
 */
public interface Model extends EObject
{
  /**
   * Returns the value of the '<em><b>Path</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Path</em>' attribute.
   * @see #setPath(String)
   * @see edu.postech.xtext.maude.maude.MaudePackage#getModel_Path()
   * @model
   * @generated
   */
  String getPath();

  /**
   * Sets the value of the '{@link edu.postech.xtext.maude.maude.Model#getPath <em>Path</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Path</em>' attribute.
   * @see #getPath()
   * @generated
   */
  void setPath(String value);

  /**
   * Returns the value of the '<em><b>Maude</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Maude</em>' attribute.
   * @see #setMaude(String)
   * @see edu.postech.xtext.maude.maude.MaudePackage#getModel_Maude()
   * @model
   * @generated
   */
  String getMaude();

  /**
   * Sets the value of the '{@link edu.postech.xtext.maude.maude.Model#getMaude <em>Maude</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Maude</em>' attribute.
   * @see #getMaude()
   * @generated
   */
  void setMaude(String value);

  /**
   * Returns the value of the '<em><b>Options</b></em>' attribute list.
   * The list contents are of type {@link java.lang.String}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Options</em>' attribute list.
   * @see edu.postech.xtext.maude.maude.MaudePackage#getModel_Options()
   * @model unique="false"
   * @generated
   */
  EList<String> getOptions();

} // Model
