
set show timing off .

load ../../interpreter-symbolic2.maude
load ../syntax/module-thermostat-event-data.maude


mod TEST-THERMOSTAT-SYSTEM-MOD is
  including THERMOSTAT-SYSTEM-SYNTAX .
  including BEHAVIOR-SYMBOLIC-LOCATION . 
  including MODEL-TRANSITION-SYSTEM .
  including SMT-REAL-EXP .
  
  eq init  = loc(real(0)) .
  eq state = loc(real(1)) .

  op initState : -> Object .
  eq initState = initialize(model) .
endm


search [,5] {bool(true) || initState | 0 | infty} =>+ C:GlobalSystem .
