/**
 * generated by Xtext 2.17.0
 */
package edu.postech.xtext.maude.ui.contentassist;

import edu.postech.xtext.maude.ui.contentassist.AbstractMaudeProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class MaudeProposalProvider extends AbstractMaudeProposalProvider {
}
