/*
 * generated by Xtext 2.17.0
 */
package edu.postech.xtext.maude.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.validation.AbstractDeclarativeValidator;

public abstract class AbstractMaudeValidator extends AbstractDeclarativeValidator {
	
	@Override
	protected List<EPackage> getEPackages() {
		List<EPackage> result = new ArrayList<EPackage>();
		result.add(edu.postech.xtext.maude.maude.MaudePackage.eINSTANCE);
		return result;
	}
}
