set show timing off .

load ../../interpreter-symbolic2-merge.maude
load ../syntax/SimpleTherm_impl_Instance.maude

mod TEST-THERMOSTAT-SYSTEM is
  including SIMPLETHERM_IMPL_INSTANCE-MODEL-SYMBOLIC .

  op initState : -> Object .
  eq initState = initialize(initial) .

  op cinitState : -> Object .
  eq cinitState = initialize(collapse(initial)) .

  eq @m@ = ['SIMPLETHERM_IMPL_INSTANCE-MODEL-SYMBOLIC] .
endm

red initState .

search [,5] {bool(true) || initState | 0 | infty} =>+ C:GlobalSystem .

search [,5] {bool(true) || cinitState | 0 | infty} =>+ C:GlobalSystem .
