set show timing off .

load ../../interpreter-symbolic.maude

select BOOL-EXP-SIMPLIFICATION .
red b(0) and ([false] or b(0)) .
red [true] and b(2) or (b(4) === [false]) .
red b(0) === b(0) ? [true] and b(2) : b(3) .
red [true] .
red not [true] .
red [true] and [false] .
red [true] xor [false] .
red [true] or [false] .
red [true] implies [false] .
red [true] === [false] .
red [true] =/== [false] .

select REAL-EXP-SIMPLIFICATION .
red ([3] * [3/4]) < r(0) .
red r(1) > r(1) ? [2] / [5] : [1] * [3] + [6] .
red [1] + [2] + [3] + (- [2]).
red [1] + [1] .
red [1] * [1] .
red [1] - [1] .
red [1] / [1] .

red [1] < [1] .
red [1] <= [1] .
red [1] > [1] .
red [1] >= [1] .
