/*
 * generated by Xtext 2.17.0
 */
package edu.postech.xtext.maude.ui;

import com.google.inject.Injector;
import edu.postech.xtext.maude.ui.internal.MaudeActivator;
import org.eclipse.core.runtime.Platform;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class MaudeExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return Platform.getBundle(MaudeActivator.PLUGIN_ID);
	}
	
	@Override
	protected Injector getInjector() {
		MaudeActivator activator = MaudeActivator.getInstance();
		return activator != null ? activator.getInjector(MaudeActivator.EDU_POSTECH_XTEXT_MAUDE_MAUDE) : null;
	}

}
