
set show timing off .

load ../../interpreter-symbolic-merge.maude
load ../symbolic/module-synchronous-model.maude


mod TEST-MODEL-TRANSITION-SYSTEM is
  including TEST-MODEL-TRANSITION-SYSTEM-MOD .

  eq @m@ = ['TEST-MODEL-TRANSITION-SYSTEM-MOD] .
endm


---------------------------------------------
select TEST-MODEL-TRANSITION-SYSTEM .

search [,50] {bool(true) || obj4 | 0 | infty} =>+ C:GlobalSystem .
