
set show timing off .

load ../../interpreter-symbolic-merge.maude
load ../syntax/module-thermostat-hie.maude


---------------------------------------------
mod TEST-THERMOSTAT-SYSTEM-HIE-MOD is
  including THERMOSTAT-SYSTEM-SYNTAX .
  including BEHAVIOR-SYMBOLIC-LOCATION . 
  including MODEL-TRANSITION-SYSTEM .
  including SMT-REAL-EXP .
  
  eq init  = loc([0]) .
  eq state = loc([1]) .

  op initState : -> Object .
  eq initState = initialize(model) .

  op cinitState : -> Object .
  eq cinitState = initialize(collapse(model)) .
endm


mod TEST-THERMOSTAT-SYSTEM-HIE is
  including TEST-THERMOSTAT-SYSTEM-HIE-MOD .

  eq @m@ = ['TEST-THERMOSTAT-SYSTEM-HIE-MOD] .
endm


search [,5] {bool(true) || initState | 0 | infty} =>+ C:GlobalSystem .

search [,5] {bool(true) || cinitState | 0 | infty} =>+ C:GlobalSystem .
