
set show timing off .

load ../../interpreter-random.maude
load ../syntax/module-thermostat-event-data-noparam.maude


mod TEST-THERMOSTAT-SYSTEM is
  including THERMOSTAT-SYSTEM-SYNTAX .
  including MODEL-TRANSITION-SYSTEM .
  
  op initConst : -> BoolExp .
  eq initConst = [true] .

  op initState : -> Object .
  eq initState = initialize(model) .
endm


rew [100] {{initState,0}} .

rew [100] {{initState,400}} .

rew [100] {{initState,800}} .

rew [100] {{initState,1200}} .
