set show timing off .

load ../../interpreter-random.maude
load ../syntax/module-thermostat-noparam.maude 

---------------------------------------------
mod TEST-THERMOSTAT-SYSTEM is
  including THERMOSTAT-SYSTEM-NOPARAM .
  including MODEL-TRANSITION-SYSTEM .

  op initState : -> Object .
  eq initState = initialize(model) .
endm

rew [100] {{initState,0}} .

rew [100] {{initState,400}} .

rew [100] {{initState,800}} .

rew [100] {{initState,1200}} .
