set show timing off .

load ../../interpreter-distributed.maude
load ../syntax/SimpleTherm_impl_Instance.maude 

---------------------------------------------
mod TEST-THERMOSTAT-SYSTEM is
  including SIMPLETHERM_IMPL_INSTANCE-MODEL .
  including MODEL-TRANSITION-SYSTEM .

  op initState : -> Object .
  eq initState = initialize(initial) .

  op cinitState : -> Object .
  eq cinitState = initialize(collapse(initial)) .

  eq #sample = 4 .
  eq #response = 4 .
endm

red initState .

red cinitState .

---set print attribute on .

rew  [100] {cinitState | 0 | infty} .

rew  [100] {cinitState | 0 | infty} .

---the number of reachable states up to 5 synchronous step
search [,5] {initState | 0 | infty} =>* {none | T:Time | infty} .

search [,5] {cinitState | 0 | infty} =>* {none | T:Time | infty} .
