mod THERMOSTAT2CON_IMPL_INSTANCE-MODEL is
	including MODEL-TRANSITION-SYSTEM .

	--- AADL identifiers
	ops tempmax currtemp offheater2 offcontrol offheater1 onheater1 oncontrol onheater2 temp2 tempmin temp1 : -> FeatureId [ctor] .
	ops x y s t : -> VarId [ctor] .
	ops console consoleProc environment ctrlThread ctrlProc Thermostat2ConimplInstance controller2 x y consoleThread controller1 : -> ComponentId [ctor] .
	ops init s00 s11 select s10 idle s01 : -> Location [ctor] .
	--- the initial state
	op initial : -> Object .
	eq initial = < Thermostat2ConimplInstance : System |
		features : (
			none),
		subcomponents : (
			< console : System |
				features : (
					< tempmax : DataOutPort |
						content : null(Real) ,
						properties : (DataModel::InitialValue => {{50}}) >
					< tempmin : DataOutPort |
						content : null(Real) ,
						properties : (DataModel::InitialValue => {{20}}) >),
				subcomponents : (
					< consoleProc : Process |
						features : (
							< tempmax : DataOutPort |
								content : null(Real) ,
								properties : none >
							< tempmin : DataOutPort |
								content : null(Real) ,
								properties : none >),
						subcomponents : (
							< consoleThread : Thread |
								features : (
									< tempmax : DataOutPort |
										content : null(Real) ,
										properties : none >
									< tempmin : DataOutPort |
										content : null(Real) ,
										properties : none >),
								subcomponents : (
									none),
								currState : (
									idle),
								completeStates : (
									idle),
								variables : (
									empty),
								transitions : (
									(idle -[ on dispatch ]-> select {
										skip
									}) ;
									(select -[ [[true]] ]-> idle {
										(f{tempmax} := [[50]]) ;
										(f{tempmin} := [[20]])
									})),
								loopBound : (
									10),
								transBound : (
									10),
								varGen : (
									< "Thermostat2ConimplInstance.console.consoleProc.consoleThread" >
									),
								properties : (
									(TimingProperties::Period => {{60}}) ;
									(HybridSynchAADL::Synchronous => {{true}})),
								connections : (
									empty)
								> ),
						properties : (
							(TimingProperties::Period => {{60}}) ;
							(HybridSynchAADL::Synchronous => {{true}})),
						connections : (
							(consoleThread .. tempmax --> tempmax) ;
							(consoleThread .. tempmin --> tempmin) ;
							(consoleThread .. tempmax --> tempmax) ;
							(consoleThread .. tempmin --> tempmin))
						> ),
				properties : (
					(TimingProperties::Period => {{60}}) ;
					(HybridSynchAADL::MaxClockDeviation => {{1.0}}) ;
					(HybridSynchAADL::Synchronous => {{true}})),
				connections : (
					(consoleProc .. tempmax --> tempmax) ;
					(consoleProc .. tempmin --> tempmin) ;
					(consoleProc .. tempmax --> tempmax) ;
					(consoleProc .. tempmin --> tempmin))
				>
			< controller1 : System |
				features : (
					< tempmax : DataInPort |
						content : null(Real) ,
						cache : null(Real),
						properties : none >
					< tempmin : DataInPort |
						content : null(Real) ,
						cache : null(Real),
						properties : none >
					< currtemp : DataInPort |
						content : null(Real) ,
						cache : null(Real),
						properties : none >
					< oncontrol : DataOutPort |
						content : null(Unit) ,
						properties : none >
					< offcontrol : DataOutPort |
						content : null(Unit) ,
						properties : none >),
				subcomponents : (
					< ctrlProc : Process |
						features : (
							< tempmax : DataInPort |
								content : null(Real) ,
								cache : null(Real),
								properties : none >
							< tempmin : DataInPort |
								content : null(Real) ,
								cache : null(Real),
								properties : none >
							< currtemp : DataInPort |
								content : null(Real) ,
								cache : null(Real),
								properties : none >
							< oncontrol : DataOutPort |
								content : null(Unit) ,
								properties : none >
							< offcontrol : DataOutPort |
								content : null(Unit) ,
								properties : none >),
						subcomponents : (
							< ctrlThread : Thread |
								features : (
									< tempmax : DataInPort |
										content : null(Real) ,
										cache : null(Real),
										properties : none >
									< tempmin : DataInPort |
										content : null(Real) ,
										cache : null(Real),
										properties : none >
									< currtemp : DataInPort |
										content : null(Real) ,
										cache : null(Real),
										properties : none >
									< oncontrol : DataOutPort |
										content : null(Unit) ,
										properties : none >
									< offcontrol : DataOutPort |
										content : null(Unit) ,
										properties : none >),
								subcomponents : (
									none),
								currState : (
									init),
								completeStates : (
									init),
								variables : (
									empty),
								transitions : (
									(init -[ on dispatch ]-> init {
										if ((f[currtemp] > f[tempmax])){
											(oncontrol !)}
										(elsif ((f[currtemp] < f[tempmin])){
											(offcontrol !)}
										)
										end if
									})),
								loopBound : (
									10),
								transBound : (
									10),
								varGen : (
									< "Thermostat2ConimplInstance.controller1.ctrlProc.ctrlThread" >
									),
								properties : (
									(TimingProperties::Period => {{60}}) ;
									(HybridSynchAADL::SamplingTime => {{1.0 .. 5.0}}) ;
									(HybridSynchAADL::ResponseTime => {{14.0 .. 15.0}}) ;
									(HybridSynchAADL::Synchronous => {{true}})),
								connections : (
									empty)
								> ),
						properties : (
							(TimingProperties::Period => {{60}}) ;
							(HybridSynchAADL::Synchronous => {{true}})),
						connections : (
							(ctrlThread .. offcontrol --> offcontrol) ;
							(currtemp --> ctrlThread .. currtemp) ;
							(tempmax --> ctrlThread .. tempmax) ;
							(ctrlThread .. oncontrol --> oncontrol) ;
							(tempmin --> ctrlThread .. tempmin))
						> ),
				properties : (
					(TimingProperties::Period => {{60}}) ;
					(HybridSynchAADL::MaxClockDeviation => {{1.0}}) ;
					(HybridSynchAADL::SamplingTime => {{1.0 .. 5.0}}) ;
					(HybridSynchAADL::ResponseTime => {{14.0 .. 15.0}}) ;
					(HybridSynchAADL::Synchronous => {{true}})),
				connections : (
					(ctrlProc .. oncontrol --> oncontrol) ;
					(tempmin --> ctrlProc .. tempmin) ;
					(currtemp --> ctrlProc .. currtemp) ;
					(tempmax --> ctrlProc .. tempmax) ;
					(ctrlProc .. offcontrol --> offcontrol))
				>
			< controller2 : System |
				features : (
					< tempmax : DataInPort |
						content : null(Real) ,
						cache : null(Real),
						properties : none >
					< tempmin : DataInPort |
						content : null(Real) ,
						cache : null(Real),
						properties : none >
					< currtemp : DataInPort |
						content : null(Real) ,
						cache : null(Real),
						properties : none >
					< oncontrol : DataOutPort |
						content : null(Unit) ,
						properties : none >
					< offcontrol : DataOutPort |
						content : null(Unit) ,
						properties : none >),
				subcomponents : (
					< ctrlProc : Process |
						features : (
							< tempmax : DataInPort |
								content : null(Real) ,
								cache : null(Real),
								properties : none >
							< tempmin : DataInPort |
								content : null(Real) ,
								cache : null(Real),
								properties : none >
							< currtemp : DataInPort |
								content : null(Real) ,
								cache : null(Real),
								properties : none >
							< oncontrol : DataOutPort |
								content : null(Unit) ,
								properties : none >
							< offcontrol : DataOutPort |
								content : null(Unit) ,
								properties : none >),
						subcomponents : (
							< ctrlThread : Thread |
								features : (
									< tempmax : DataInPort |
										content : null(Real) ,
										cache : null(Real),
										properties : none >
									< tempmin : DataInPort |
										content : null(Real) ,
										cache : null(Real),
										properties : none >
									< currtemp : DataInPort |
										content : null(Real) ,
										cache : null(Real),
										properties : none >
									< oncontrol : DataOutPort |
										content : null(Unit) ,
										properties : none >
									< offcontrol : DataOutPort |
										content : null(Unit) ,
										properties : none >),
								subcomponents : (
									none),
								currState : (
									init),
								completeStates : (
									init),
								variables : (
									empty),
								transitions : (
									(init -[ on dispatch ]-> init {
										if ((f[currtemp] > f[tempmax])){
											(oncontrol !)}
										(elsif ((f[currtemp] < f[tempmin])){
											(offcontrol !)}
										)
										end if
									})),
								loopBound : (
									10),
								transBound : (
									10),
								varGen : (
									< "Thermostat2ConimplInstance.controller2.ctrlProc.ctrlThread" >
									),
								properties : (
									(TimingProperties::Period => {{60}}) ;
									(HybridSynchAADL::SamplingTime => {{3.0 .. 8.0}}) ;
									(HybridSynchAADL::ResponseTime => {{30.0 .. 35.0}}) ;
									(HybridSynchAADL::Synchronous => {{true}})),
								connections : (
									empty)
								> ),
						properties : (
							(TimingProperties::Period => {{60}}) ;
							(HybridSynchAADL::Synchronous => {{true}})),
						connections : (
							(ctrlThread .. offcontrol --> offcontrol) ;
							(tempmin --> ctrlThread .. tempmin) ;
							(ctrlThread .. oncontrol --> oncontrol) ;
							(tempmax --> ctrlThread .. tempmax) ;
							(currtemp --> ctrlThread .. currtemp))
						> ),
				properties : (
					(TimingProperties::Period => {{60}}) ;
					(HybridSynchAADL::MaxClockDeviation => {{1.0}}) ;
					(HybridSynchAADL::SamplingTime => {{3.0 .. 8.0}}) ;
					(HybridSynchAADL::ResponseTime => {{30.0 .. 35.0}}) ;
					(HybridSynchAADL::Synchronous => {{true}})),
				connections : (
					(tempmax --> ctrlProc .. tempmax) ;
					(ctrlProc .. oncontrol --> oncontrol) ;
					(tempmin --> ctrlProc .. tempmin) ;
					(currtemp --> ctrlProc .. currtemp) ;
					(ctrlProc .. offcontrol --> offcontrol))
				>
			< environment : Env |
				features : (
					< temp1 : EnvOutPort |
						content : [[15]],
						target : controller1,
						properties : (DataModel::InitialValue => {{15}}),
						envCache : [[15]] >
					< temp2 : EnvOutPort |
						content : [[15]],
						target : controller2,
						properties : (DataModel::InitialValue => {{15}}),
						envCache : [[15]] >
					< onheater1 : EnvInPort |
						content : null(Unit),
						properties : none,
						envCache : null(Unit) >
					< offheater1 : EnvInPort |
						content : null(Unit),
						properties : none,
						envCache : null(Unit) >
					< onheater2 : EnvInPort |
						content : null(Unit),
						properties : none,
						envCache : null(Unit) >
					< offheater2 : EnvInPort |
						content : null(Unit),
						properties : none,
						envCache : null(Unit) >),
				subcomponents : (
					< x : Data |
						features : (
							none),
						subcomponents : (
							none),
						value : null(Real),
						properties : (
							(DataModel::InitialValue => {{15}})),
						connections : (
							empty)
						>
					< y : Data |
						features : (
							none),
						subcomponents : (
							none),
						value : null(Real),
						properties : (
							(DataModel::InitialValue => {{15}})),
						connections : (
							empty)
						> ),
				currMode : (
					s00
					),
				jumps : (
					(s00 -[ onheater1 ]-> s10) ;
					(s00 -[ onheater2 ]-> s01) ;
					(s01 -[ onheater1 ]-> s11) ;
					(s01 -[ offheater2 ]-> s00) ;
					(s10 -[ offheater1 ]-> s00) ;
					(s10 -[ onheater2 ]-> s11) ;
					(s11 -[ offheater1 ]-> s01) ;
					(s11 -[ offheater2 ]-> s10)
					),
				flows : (
					((s11)[x(t) = [[0.1]] * (([[45.0]] + [[30.0]]) * v[t] - c[x]) ; y(s) = [[0.1]] * (([[45.0]] + [[30.0]]) * v[s] - c[y])]) ;
					((s00)[x(t) = [[0.1]] * (([[45.0]] + [[30.0]]) * v[t] - c[x]) ; y(s) = [[0.1]] * (- c[y]) * v[s]]) ;
					((s01)[x(t) = [[0.1]] * (- c[x]) * v[t] ; y(s) = [[0.1]] * (([[45.0]] + [[30.0]]) * v[s] - c[y])]) ;
					((s11)[x(t) = [[0.1]] * (- c[x]) * v[t] ; y(s) = [[0.1]] * (- c[y]) * v[s]]) ;
					),
				sampling : (
					(controller1 : (rat(1.0),rat(5.0))) ;
					(controller2 : (rat(3.0),rat(8.0)))
					),
				response : (
					(controller1 : (rat(14.0),rat(15.0))) ;
					(controller2 : (rat(30.0),rat(35.0)))
					),
				varGen : (
					< "Thermostat2ConimplInstance.environment" >
					),
				properties : (
					(TimingProperties::Period => {{60}}) ;
					(HybridSynchAADL::MaxClockDeviation => {{1.0}}) ;
					(HybridSynchAADL::Synchronous => {{true}})),
				connections : (
					(y ==> temp2) ;
					(x ==> temp1))
				> ),
		properties : (
			(TimingProperties::Period => {{60}}) ;
			(HybridSynchAADL::MaxClockDeviation => {{1.0}}) ;
			(HybridSynchAADL::Synchronous => {{true}})),
		connections : (
			(controller2 .. oncontrol --> environment .. onheater2) ;
			(console .. tempmin --> controller2 .. tempmin) ;
			(controller1 .. offcontrol --> environment .. offheater1) ;
			(environment .. temp2 --> controller2 .. currtemp) ;
			(console .. tempmax --> controller2 .. tempmax) ;
			(controller2 .. offcontrol --> environment .. offheater2) ;
			(controller1 .. oncontrol --> environment .. onheater1) ;
			(console .. tempmin --> controller1 .. tempmin) ;
			(console .. tempmax --> controller1 .. tempmax) ;
			(environment .. temp1 --> controller1 .. currtemp))
		>  .
endm

mod THERMOSTAT2CON_IMPL_INSTANCE-MODEL-SYMBOLIC is
	including THERMOSTAT2CON_IMPL_INSTANCE-MODEL .
	including BEHAVIOR-SYMBOLIC-LOCATION .

	eq init = loc(real(0)) .
	eq s00 = loc(real(1)) .
	eq s11 = loc(real(2)) .
	eq select = loc(real(3)) .
	eq s10 = loc(real(4)) .
	eq idle = loc(real(5)) .
	eq s01 = loc(real(6)) .
endm
