/**
 * generated by Xtext 2.17.0
 */
package edu.postech.xtext.maude;

import edu.postech.xtext.maude.AbstractMaudeRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class MaudeRuntimeModule extends AbstractMaudeRuntimeModule {
}
