
set show timing off .

load ../../interpreter-smt-check-symbolic.maude
load ../syntax/module-thermostat-hie.maude


---------------------------------------------
mod TEST-THERMOSTAT-SYSTEM-HIE-MOD is
  including THERMOSTAT-SYSTEM-SYNTAX .
  including BEHAVIOR-SYMBOLIC-LOCATION .
  including MODEL-TRANSITION-SYSTEM .
  including SMT-REAL-EXP .

  eq init  = loc([0]) .
  eq state = loc([1]) .

  op initConst : -> BoolExp .
  eq initConst =
        [true] .

  op initState : -> Object .
  eq initState = initialize(model) .

  op cinitState : -> Object .
  eq cinitState = initialize(collapse(model)) .
endm


mod TEST-THERMOSTAT-SYSTEM-HIE is
  including TEST-THERMOSTAT-SYSTEM-HIE-MOD .

  eq @m@ = ['TEST-THERMOSTAT-SYSTEM-HIE-MOD] .
  eq MFlag = true .
endm


search {initConst || initState, 0, 5} =>+ C:GlobalSystem .

search {initConst || initState, 0, 5} =>+ C:GlobalSystem .

search {initConst || cinitState, 0, 5} =>+ C:GlobalSystem .

search {initConst || cinitState, 0, 5} =>+ C:GlobalSystem .
