set show timing off .

load ../../interpreter-distributed.maude
load ../syntax/Thermostat_impl_Instance.maude 

---------------------------------------------
mod TEST-THERMOSTAT-SYSTEM is
  including THERMOSTAT_IMPL_INSTANCE-MODEL .
  including MODEL-TRANSITION-SYSTEM .

  var T : Time .

  op initState : -> Object .
  eq initState = initialize(initial) .

  op cinitState : -> Object .
  eq cinitState = initialize(collapse(initial)) .
endm

--- set print attribute on .

rew  [100] {initState | 0 | infty} .

rew  [100] {cinitState | 0 | infty} .

--- the number of reachable states up to 5 synchronous step
search {initState | 0 | 25} =>* {none | T | 25} .

search {cinitState | 0 | 25} =>* {none | T | 25} .
