set show timing off .

load ../../interpreter-distributed.maude
load ../syntax/Drones2_impl_Instance.maude .

mod TEST-DRONE2-SYSTEM is
  including DRONES2_IMPL_INSTANCE-MODEL .
  including MODEL-TRANSITION-SYSTEM .

  var T : Time .

  op initState : -> Object .
  eq initState = initialize(initial) .

  op cinitState : -> Object .
  eq cinitState = initialize(collapse(initial)) .

endm


--- set print attribute on .

rew  [100] {initState | 0 | infty} .

rew  [100] {cinitState | 0 | infty} .

--- the number of reachable states up to 1 synchronous step
search {initState | 0 | 30} =>* {none | T | 30} .

search {cinitState | 0 | 30} =>* {none | T | 30} .
